= Deploy and Scale a Simple App

== Goal

Deploy a simple Spring Boot app, scale it, check its logs and SSH into a container.

Approximate time: 15 minutes

== Exercises

=== Push a simple Spring Boot app

. In the cf CLI, make sure you are targeting the lab’s PCF installation and development space.

. In the cf CLI, verify that the lab’s PCF installation includes a Java buildpack (use cf help if needed).

. In your home directory on your computer, create a pcf-labs directory. 

. Download the Spring Music app from `https://github.com/scottfrederick/spring-music/archive/master.zip`

. Copy the zip file downloaded into the directory you created above and extract the contents.

. Change directory to ~/pcf-labs/spring-music-master

. In a terminal window, *change to the directory containing the extracted zip file (i.e.  ~/pcf-labs/spring-music-master). Run `/gradlew assemble` to build the application.

. Run `cf push` to deploy the application.

. Use the cf CLI to verify that your app is now in the development space.

. View the app in the PCF's Apps Manager.

. View the execution of the app in a browser (the link is in Apps Manager).

=== Scale the app

. Using Apps Manager, increase the number of instances for you app to 2. Notice how quick this is, since the droplet just needs to be copied to a new container.

. Using the cf CLI, decrease the number of instances for your app back to 1.

=== View logs and events for the app

. In Apps Manager, select your application and view the logs and events.

. Using the cf CLI, tail the logs for your app (due to company firewall restrictions, this
may not work - if not, you can also tail logs using the Apps Manager)

. Refresh your browser for the app to generate a log entry. Use CTRL C to stop the tailing.

=== SSH into a Container

. (This exercise assumes that you are on an environment that has enabled SSH container access, such as PWS.) Use the cf CLI to access the first instance
of your application's container. `cf ssh <app name`. Browse the container. Type `exit` to exit the SSH session.

Congratulations, you have pushed an application, scaled it, viewed its logs and SSH'd into a container.
