= Domains and Routes- Update an App with Continuous Availability

== Goal

Use routes to perform an application upgrade with blue/green deployment.

Approximate time: 15 minutes

== Exercises

=== Push a simple Spring Boot app

. cf push your simple Spring Boot application. Use your browser to verify that while you stage (push) the app, your application is down.

. Use Apps Manager or the CLI to view the route for your simple Spring Boot application. We want this route to always contain a working application, even though we will upgrade the application's version.

. Modify the header.html file located in the ~/pcf-labs/spring-music-master/src/main/webapp/assets/templates directory and add Version 2 next to the Spring Music text in the <a> ref.

....
<a class="navbar-brand" href="#">Spring Music Version 2<span class="glyphicon glyphicon-music"></span></a>
....

. Change directory to ~/pcf-labs/spring-music-master and rebuild the application.  Run `./gradlew assemble` 

. Modify the manifest file located in ~/pcf-labs/spring-music-master and append 2 to the name and host like below.

....
---
applications:
- name: spring-music2
  memory: 512M
  instances: 1
  host: spring-music2-${random-word}
  path: build/libs/spring-music.war
....

. cf push this version of the application, naming it the same as the new directory name. Verify that you now have two different applications with two different routes.

. In a browser, access your version 2 application on its unique route.

. Let's assume your application is now ready to upgrade. Add a route on your version 2 app to point to the route on the version 1 app.  Refresh your browser a few times using the original route. Notice that both versions are sometimes displayed.

. Remove the route to the version 1 application. Now on the original route, you should only see version 2 of the application. The end users never experienced any downtime.
